### ISSUE TITLE
And if we can't right-click?

### ISSUE THREAD

**Issue by jaygoodswp** [AstroCB/StopScroll-Extension#1]
Is there any place on the main menu where we can click on "Stop Scrolling"?  The context menu is great but as you know, some web pages don't allow access to the context menu (like games).

**Comment by AstroCB** [comment]
What do you mean by the "main menu"? Are you talking about the icon in the toolbar?

I assume you're using this in Chrome since the Firefox and Safari builds don't have an icon there and only use the context menu as far as I recall.

It shouldn't be too tricky to add the actions to that menu if that's what you're referring to.

**Comment by jaygoodswp** [comment]
yes - ok, thanks

**Comment by AstroCB** [comment]
You can now toggle scrolling by right-clicking on the extension's menu bar icon in Chrome.
